
[package]
name             = "gdk-pixbuf"
version          = "2.44.8"
description      = "GTK image loading library"
license          = "LGPL-2.1-or-later"
maintainer       = "Zainium Dynamics <alizain@zainiumdynamics.tech>"
homepage         = "https://gitlab.gnome.org/GNOME/gdk-pixbuf"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

requires_syshub  = ""
depends          = ["musl", "glib", "libpng", "libjpeg-turbo"]
provides         = ["gdk-pixbuf"]
tags             = ["library", "gnome", "graphics"]

[install]
bin     = "/overlayer/zexlib/union/bin"
lib     = "/overlayer/zexlib/union/lib"
_syshub = false

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
