[package]
name             = "hello"
version          = "2.12.1"
description      = "GNU Hello — canonical example package"
license          = "GPL-3.0-or-later"
maintainer       = "Ali Zain <heyalizain@gmail.com>"
homepage         = "https://www.gnu.org/software/hello/"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

requires_syshub  = ""
depends          = ["musl"]
provides         = ["hello"]
tags             = ["utility", "example"]

[install]
bin     = "/overlayer/zexlib/union/bin"
lib     = "/overlayer/zexlib/union/lib"
etc     = "/overlayer/zexlib/union/etc"
share   = "/overlayer/zexlib/union/share"
var     = "/overlayer/zexlib/union/var"
_syshub = false

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
