# manifest.toml — lz4
# See substrate's USAGE.md for the full field reference.

[package]
name             = "lz4"
version          = "1.10.0"
description      = "Extremely fast compression algorithm"
license          = "BSD-2-Clause AND GPL-2.0-or-later"
maintainer       = "Zainium Dynamics <alizain@zainiumdynamics.tech>"
homepage         = "https://github.com/lz4/lz4"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

requires_syshub  = ""
depends          = ["musl"]
provides         = ["lz4"]
tags             = ["compression", "library"]

[install]
bin     = "/overlayer/zexlib/union/bin"
lib     = "/overlayer/zexlib/union/lib"
_syshub = false

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
