[package]
name             = "spirv-llvm-translator-dev"
version          = "22.1.0"
description      = "LLVMSPIRVLib static lib, headers, pkgconfig"
license          = "NCSA"
maintainer       = "Zainium Dynamics <alizain@zainiumdynamics.tech>"
homepage         = "https://github.com/KhronosGroup/SPIRV-LLVM-Translator"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["spirv-llvm-translator", "llvm-dev"]
provides         = ["spirv-llvm-translator-dev"]
tags             = ["graphics", "dev"]

[install]
include = "/overlayer/zexlib/union/include"
lib     = "/overlayer/zexlib/union/lib"
_syshub = false

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
