[package]
name             = "python"
version          = "3.14.6"
description      = "Python 3 interpreter"
license          = "PSF-2.0"
maintainer       = "Zainium Dynamics <alizain@zainiumdynamics.tech>"
homepage         = "https://www.python.org/"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["libffi"]
provides         = ["python"]
tags             = ["language", "runtime"]

[install]
bin     = "/overlayer/zexlib/union/bin"
lib     = "/overlayer/zexlib/union/lib"
share   = "/overlayer/zexlib/union/share"
_syshub = false

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
